name: Bug report
description: File a bug report
title: "[Bug]: title"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Same issue exist?
      options:
        - label: I have searched the issues (https://github.com/dbkangaroo/kangaroo/issues)
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version do you using?
      options:
        - 3.93.1
        - 3.99.1
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Which branch do you using?
      options:
        - Multiple
        - SQLite
        - MySQL
        - MariaDB
        - PostgreSQL
  - type: dropdown
    id: platform
    attributes:
      label: Windows
      description: Which platform do you using?
      options:
        - Windows
        - macOS
        - Linux
        - Others
  - type: textarea
    attributes:
      label: Bug detail
      description: Please share the bug environment, key steps, data and screenshot, expection and solution, thanks.
      placeholder: |
        1. Environment
        2. Reproduce steps
        3. Data and screenshot
        4. Expection and solution
    validations:
      required: true
