name: Bug report
description: File a bug report
title: "[Bug]: title"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Same issue exist?
      options:
        - label: I have searched the issues (https://github.com/dbkangaroo/kangaroo/issues)
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version of Kangaroo
      description: Which version of Kangaroo do you using?
      options:
        - 5.0.0
        - 4.99.9
        - 4.99.1
        - 4.98.1
        - 4.0.0
        - 3.99.2
        - 3.99.1
        - 3.93.1
        - others
  - type: dropdown
    id: branch
    attributes:
      label: Branch of Kangaroo
      description: Which branch of Kangaroo do you using?
      options:
        - Multiple
        - SQLite
        - MySQL
        - MariaDB
        - PostgreSQL
        - SQLServer
  - type: dropdown
    id: platform
    attributes:
      label: Platform of Kangaroo
      description: Which platform does Kangaroo run on it?
      options:
        - Windows (x86-64)
        - Windows (aarch64)
        - macOS (aarch64)
        - macOS (x86-64)
        - Linux (x86-64)
        - Linux (aarch64)
        - Linux (riscv64)
        - Linux (loongarch64)
        - Others
  - type: textarea
    attributes:
      label: Bug detail
      description: Please share the bug environment, key steps, data and screenshot, expection and solution, thanks.
      placeholder: |
        1. Environment
        2. Reproduce steps
        3. Data and screenshot
        4. Expection and solution
    validations:
      required: true
