blank_issues_enabled: false
contact_links:
  - name: Kangaroo document
    url: https://www.datatable.online/en/document/
    about: Please ask and answer questions here.
  - name: Kangaroo Community Support
    url: https://github.com/dbkangaroo/kangaroo/discussions
    about: Please ask and answer questions here.
